"use client";
import { create } from "zustand";
import { fetchPlaylist } from "@/lib/youtube";
import { getCourseData, getProgress, setCourseData, upsertCourse } from "@/lib/storage";
import type { CourseData, Playlist, StoredCourse, Video } from "@/types/youtube";
interface CourseState { playlist: Playlist | null; videos: Video[]; completedVideos: string[]; courses: Record<string, StoredCourse>; dailyTargetMinutes: number; loading: boolean; error: string | null; loadPlaylist: (id: string) => Promise<void>; loadCourses: () => void; toggleVideoComplete: (id: string) => void; updateDailyTarget: (minutes: number) => void; resetProgress: () => void; exportData: () => void; importData: (data: CourseData, replace: boolean) => void; }
const day = () => new Date().toISOString().slice(0, 10);
export const useCourseStore = create<CourseState>((set, get) => ({ playlist: null, videos: [], completedVideos: [], courses: {}, dailyTargetMinutes: 60, loading: false, error: null,
  loadCourses() { set({ courses: getCourseData().courses }); },
  async loadPlaylist(id) { set({ loading: true, error: null, playlist: null, videos: [] }); try { const { playlist, videos } = await fetchPlaylist(id); const existing = getCourseData().courses[id]; const course: StoredCourse = existing ?? { playlistId: id, title: playlist.title, channel: playlist.channelTitle, thumbnailUrl: playlist.thumbnail.url, videoCount: playlist.itemCount, dailyTargetMinutes: 60, completedVideos: getProgress(id).completedVideos, createdAt: day(), lastOpenedAt: day() }; const updated = { ...course, title: playlist.title, channel: playlist.channelTitle, thumbnailUrl: playlist.thumbnail.url, videoCount: playlist.itemCount, lastOpenedAt: day() }; upsertCourse(updated); set({ playlist, videos, completedVideos: updated.completedVideos, dailyTargetMinutes: updated.dailyTargetMinutes, courses: getCourseData().courses, loading: false }); } catch (error) { set({ error: error instanceof Error ? error.message : "Something went wrong loading this playlist.", loading: false }); } },
  toggleVideoComplete(id) { const { playlist, completedVideos, videos } = get(); if (!playlist) return; const next = completedVideos.includes(id) ? completedVideos.filter((videoId) => videoId !== id) : [...completedVideos, id]; const course = getCourseData().courses[playlist.id]; if (course) upsertCourse({ ...course, completedVideos: next, completedAt: next.length === videos.length ? day() : undefined }); set({ completedVideos: next, courses: getCourseData().courses }); },
  updateDailyTarget(minutes) { const { playlist } = get(); if (!playlist || minutes < 1) return; const course = getCourseData().courses[playlist.id]; if (course) upsertCourse({ ...course, dailyTargetMinutes: minutes }); set({ dailyTargetMinutes: minutes, courses: getCourseData().courses }); },
  resetProgress() { const { playlist } = get(); if (!playlist) return; const course = getCourseData().courses[playlist.id]; if (course) upsertCourse({ ...course, completedVideos: [], completedAt: undefined }); set({ completedVideos: [], courses: getCourseData().courses }); },
  exportData() { const blob = new Blob([JSON.stringify(getCourseData(), null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "youtube-course-backup.json"; link.click(); URL.revokeObjectURL(url); },
  importData(data, replace) { const current = getCourseData(); const next = { courses: replace ? data.courses : { ...current.courses, ...data.courses } }; setCourseData(next); set({ courses: next.courses }); }
}));
